name: LTE-Calc

services:
  frontend:
    build:
      context: ./LTE-Calc
      dockerfile: Dockerfile
    container_name: LTE-Calc_frontend
    expose:
      - "8080"
    restart: unless-stopped
    networks: [ WebSite ]

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: LTE-Calc_backend
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      - redis
    networks: [ WebSite ]

  redis:
    image: redis:7-alpine
    container_name: LTE-Calc_redis
    expose:
      - "6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks: [ WebSite ]

networks:
  WebSite:
    external: true

volumes:
  redis_data:
